name: asset-telemetry-services

networks:
  asset-telemetry-network:

volumes:
  mysql-data:
  prometheus-data:
  grafana-data:

services:
  mysql:
    image: mysql:latest
    networks:
      asset-telemetry-network:
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: greenko_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-P", "3306", "--silent"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 20s
    volumes:
      - mysql-data:/var/lib/mysql

  asset-service:
    ports:
      - "8081:8080"
    image: asset-service
    environment:
      SPRING_PROFILES_ACTIVE: dev
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: greenko_db
      CONFIG_SERVER_HOST: config-server
      CONFIG_SERVER_PORT: 8888
    networks:
      asset-telemetry-network:
    depends_on:
      config-server:
        condition: service_healthy
#      mysql:
#        condition: service_healthy


  telemetry-service:
    ports:
      - "8082:8080"
    image: telemetry-service
    networks:
      asset-telemetry-network:
    environment:
      ASSET_SERVICE_URL: http://asset-service:8080
    depends_on:
      mysql:
        condition: service_healthy

  gateway-service:
    ports:
      - "8080:8080"
    image: gateway-service
    networks:
      asset-telemetry-network:
    environment:
      ASSET_SERVICE_URL: http://asset-service:8080
      TELEMETRY_SERVICE_URL: http://telemetry-service:8080

  config-server:
    ports:
      - "8888:8888"
    image: config-server:latest
    networks:
      asset-telemetry-network:
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:8888/actuator/health/readiness" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 30s


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - asset-telemetry-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - asset-telemetry-network
    volumes:
      - grafana-data:/var/lib/grafana

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: cadvisor
    ports:
      - "8085:8080"
    networks:
      - asset-telemetry-network
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /sys:/sys:ro



  docker-stats-exporter:
    image: wywywywy/docker_stats_exporter
    ports:
      - "9487:9487"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - asset-telemetry-network
