spring:
  application:
    name: auth-app

  datasource:
    url: jdbc:h2:mem:authdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update


auth:
  jwtExpirationMs: 20000000
  jwtSecret: changeit1234567890changeit1234567890changeit1234567890changeit1234567890changeit1234567890
