name: asset-telemetry-services

networks:
  asset-telemetry-network:

services:
#  mysql:
#    image: mysql:latest
#    networks:
#      asset-telemetry-network:
#    environment:
#      MYSQL_ROOT_PASSWORD: password
#      MYSQL_DATABASE: greenko_db

  asset-service:
    ports:
      - "8081:8080"
    image: asset-service
    environment:
      SPRING_PROFILES_ACTIVE: dev
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: greenko_db
    networks:
      asset-telemetry-network:
#    depends_on:
#      - mysql
    restart: always

  telemetry-service:
    ports:
      - "8082:8080"
    image: telemetry-service
    networks:
      asset-telemetry-network:
    environment:
      ASSET_SERVICE_URL: http://asset-service:8080

  gateway-service:
    ports:
      - "8080:8080"
    image: gateway-service
    networks:
      asset-telemetry-network:
    environment:
      ASSET_SERVICE_URL: http://asset-service:8080
      TELEMETRY_SERVICE_URL: http://telemetry-service:8080

