spring:
  application:
    name: telemetry-service

  profiles:
    active: dev

#springdoc:
#  api-docs:
#    path: /v3/api-docs
#  swagger-ui:
#    path: /swagger-ui.html
#    use-root-path: true





