global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: [ 'cadvisor:8080' ]

  - job_name: 'docker-stats-exporter'
    static_configs:
      - targets: [ 'docker-stats-exporter:9487' ]

  - job_name: 'asset-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - labels:
          service: 'asset-service'
        targets: [ 'asset-service:8080' ]


