spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: asset-service
              uri: ${ASSET_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/assets/**, /web/assets/**


            - id: telemetry-service
              uri: ${TELEMETRY_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/api/telemetry/**, /web/telemetry/**


