spring:
  datasource:
    url: jdbc:h2:mem:telemetry
    username: sa
    password:


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
server:
  port: 8082



resilience4j:
  retry:
    instances:
      assetServiceRetry:
        max-attempts: 3
        wait-duration: 1s
    retry-aspect-order: 2
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    instances:
      assetService:
        register-health-indicator: true
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        sliding-window-size: 10
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 1
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-type: count_based

  ratelimiter:
    instances:
      assetServiceRateLimiter:
        limit-for-period: 10
        limit-refresh-period: 60s
        timeout-duration: 0
        register-health-indicator: true
#
#  bulkhead:
#    instances:
#      stock-service:
#        max-concurrent-calls: 5
#        max-wait-duration: 100ms
